# Generated by Django 4.2.4 on 2024-03-16 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_technology_alter_projectimage_project_project_techs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='about',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='project',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='project',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='title_ru',
        ),
        migrations.AddField(
            model_name='technology',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='technology',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
